# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_tp1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 689)
        Dialog.setStyleSheet("background-color:    rgb(212,213,217);")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(29, 9, 231, 61))
        self.title_label.setStyleSheet("font: 25pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label.setObjectName("title_label")
        self.title_label_2 = QtWidgets.QLabel(Dialog)
        self.title_label_2.setGeometry(QtCore.QRect(254, 32, 60, 30))
        self.title_label_2.setStyleSheet("font: 12pt \"Segoe Script\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_2.setObjectName("title_label_2")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(-1, -1, 371, 81))
        self.graphicsView.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(-1, 77, 371, 131))
        self.graphicsView_4.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_validacion = QtWidgets.QLabel(Dialog)
        self.label_validacion.setGeometry(QtCore.QRect(19, 88, 131, 21))
        self.label_validacion.setStyleSheet("font: 15pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_validacion.setObjectName("label_validacion")
        self.input_espesor = QtWidgets.QLineEdit(Dialog)
        self.input_espesor.setGeometry(QtCore.QRect(449, 103, 91, 21))
        self.input_espesor.setObjectName("input_espesor")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(554, -3, 191, 211))
        self.graphicsView_3.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 100, 61, 21))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 100, 81, 21))
        self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(380, 100, 81, 21))
        self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(366, -3, 191, 211))
        self.graphicsView_2.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(380, 70, 71, 21))
        self.label_10.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.lista_materiales = QtWidgets.QComboBox(Dialog)
        self.lista_materiales.setGeometry(QtCore.QRect(450, 70, 91, 22))
        self.lista_materiales.setObjectName("lista_materiales")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_6.setGeometry(QtCore.QRect(0, 200, 746, 491))
        self.graphicsView_6.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.title_label_3 = QtWidgets.QLabel(Dialog)
        self.title_label_3.setGeometry(QtCore.QRect(20, 210, 231, 51))
        self.title_label_3.setStyleSheet("font: 20pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_3.setObjectName("title_label_3")
        self.label_main_data_6 = QtWidgets.QLabel(Dialog)
        self.label_main_data_6.setGeometry(QtCore.QRect(20, 657, 531, 21))
        self.label_main_data_6.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(212, 13, 6);")
        self.label_main_data_6.setObjectName("label_main_data_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(570, 53, 161, 81))
        self.textBrowser_2.setStyleSheet("border: 0px;\n"
"\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(18, 258, 711, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.boton_guardar = QtWidgets.QPushButton(Dialog)
        self.boton_guardar.setGeometry(QtCore.QRect(610, 150, 75, 23))
        self.boton_guardar.setObjectName("boton_guardar")
        self.label_validacion_2 = QtWidgets.QLabel(Dialog)
        self.label_validacion_2.setGeometry(QtCore.QRect(410, 20, 111, 21))
        self.label_validacion_2.setStyleSheet("font: 15pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_validacion_2.setObjectName("label_validacion_2")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(380, 130, 21, 21))
        self.label_14.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(380, 160, 71, 21))
        self.label_15.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.input_L1 = QtWidgets.QLineEdit(Dialog)
        self.input_L1.setGeometry(QtCore.QRect(409, 133, 131, 21))
        self.input_L1.setObjectName("input_L1")
        self.input_L2 = QtWidgets.QLineEdit(Dialog)
        self.input_L2.setGeometry(QtCore.QRect(409, 163, 131, 21))
        self.input_L2.setObjectName("input_L2")
        self.label_validacion_3 = QtWidgets.QLabel(Dialog)
        self.label_validacion_3.setGeometry(QtCore.QRect(610, 20, 111, 21))
        self.label_validacion_3.setStyleSheet("font: 15pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_validacion_3.setObjectName("label_validacion_3")
        self.boton_graficar = QtWidgets.QPushButton(Dialog)
        self.boton_graficar.setGeometry(QtCore.QRect(654, 657, 75, 23))
        self.boton_graficar.setObjectName("boton_graficar")
        self.modelo_crammer = QtWidgets.QCheckBox(Dialog)
        self.modelo_crammer.setGeometry(QtCore.QRect(59, 123, 91, 17))
        self.modelo_crammer.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.modelo_crammer.setObjectName("modelo_crammer")
        self.modelo_sharp = QtWidgets.QCheckBox(Dialog)
        self.modelo_sharp.setGeometry(QtCore.QRect(59, 163, 91, 17))
        self.modelo_sharp.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.modelo_sharp.setObjectName("modelo_sharp")
        self.modelo_davy = QtWidgets.QCheckBox(Dialog)
        self.modelo_davy.setGeometry(QtCore.QRect(219, 123, 91, 17))
        self.modelo_davy.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.modelo_davy.setObjectName("modelo_davy")
        self.modelo_ISO = QtWidgets.QCheckBox(Dialog)
        self.modelo_ISO.setGeometry(QtCore.QRect(219, 163, 111, 17))
        self.modelo_ISO.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.modelo_ISO.setObjectName("modelo_ISO")
        self.boton_limpiar = QtWidgets.QPushButton(Dialog)
        self.boton_limpiar.setGeometry(QtCore.QRect(569, 657, 75, 23))
        self.boton_limpiar.setObjectName("boton_limpiar")
        self.graphicsView_3.raise_()
        self.graphicsView_4.raise_()
        self.graphicsView.raise_()
        self.title_label.raise_()
        self.title_label_2.raise_()
        self.label_validacion.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.graphicsView_2.raise_()
        self.label_10.raise_()
        self.lista_materiales.raise_()
        self.graphicsView_6.raise_()
        self.title_label_3.raise_()
        self.label_main_data_6.raise_()
        self.textBrowser_2.raise_()
        self.frame.raise_()
        self.boton_guardar.raise_()
        self.label_validacion_2.raise_()
        self.label_5.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.input_espesor.raise_()
        self.input_L1.raise_()
        self.input_L2.raise_()
        self.label_validacion_3.raise_()
        self.boton_graficar.raise_()
        self.modelo_crammer.raise_()
        self.modelo_sharp.raise_()
        self.modelo_davy.raise_()
        self.modelo_ISO.raise_()
        self.boton_limpiar.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Acoustic Data"))
        self.title_label_2.setText(_translate("Dialog", "panels"))
        self.label_validacion.setText(_translate("Dialog", "Modelos"))
        self.label_5.setText(_translate("Dialog", "Espesor:"))
        self.label_4.setText(_translate("Dialog", "Ancho (W):"))
        self.label_3.setText(_translate("Dialog", "Altura (H):"))
        self.label_10.setText(_translate("Dialog", "Material:"))
        self.title_label_3.setText(_translate("Dialog", "Gráfico Modelos"))
        self.label_main_data_6.setText(_translate("Dialog", "Error: Input tiene que ser tanto"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Si se ingresaron datos validos de entrada, el boton guardar genera un excel con los valores obtenidos de los modelos elegidos. </p></body></html>"))
        self.boton_guardar.setText(_translate("Dialog", "Guardar"))
        self.label_validacion_2.setText(_translate("Dialog", "Materiales"))
        self.label_14.setText(_translate("Dialog", "L1:"))
        self.label_15.setText(_translate("Dialog", "L2:"))
        self.label_validacion_3.setText(_translate("Dialog", "Guardar"))
        self.boton_graficar.setText(_translate("Dialog", "Graficar"))
        self.modelo_crammer.setText(_translate("Dialog", "Crammer"))
        self.modelo_sharp.setText(_translate("Dialog", "Sharp"))
        self.modelo_davy.setText(_translate("Dialog", "Davy"))
        self.modelo_ISO.setText(_translate("Dialog", "ISO 12354-1"))
        self.boton_limpiar.setText(_translate("Dialog", "Limpiar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
