# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_tp3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1023, 687)
        Dialog.setStyleSheet("background-color:    rgb(212,213,217);")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(29, 9, 231, 61))
        self.title_label.setStyleSheet("font: 25pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label.setObjectName("title_label")
        self.title_label_2 = QtWidgets.QLabel(Dialog)
        self.title_label_2.setGeometry(QtCore.QRect(254, 32, 60, 30))
        self.title_label_2.setStyleSheet("font: 12pt \"Segoe Script\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_2.setObjectName("title_label_2")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(-1, -1, 441, 81))
        self.graphicsView.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(-1, 77, 441, 131))
        self.graphicsView_4.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.mostrar_archivo = QtWidgets.QLabel(Dialog)
        self.mostrar_archivo.setGeometry(QtCore.QRect(160, 157, 161, 21))
        self.mostrar_archivo.setStyleSheet("border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.mostrar_archivo.setText("")
        self.mostrar_archivo.setObjectName("mostrar_archivo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(19, 138, 191, 51))
        self.label.setStyleSheet("font: 13pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label.setObjectName("label")
        self.browse_button = QtWidgets.QPushButton(Dialog)
        self.browse_button.setGeometry(QtCore.QRect(340, 157, 75, 23))
        self.browse_button.setStyleSheet("background-color:  rgb(246, 246, 244);")
        self.browse_button.setObjectName("browse_button")
        self.label_validacion = QtWidgets.QLabel(Dialog)
        self.label_validacion.setGeometry(QtCore.QRect(20, 88, 191, 51))
        self.label_validacion.setStyleSheet("font: 13pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_validacion.setObjectName("label_validacion")
        self.label_validado_o_no = QtWidgets.QLabel(Dialog)
        self.label_validado_o_no.setGeometry(QtCore.QRect(190, 104, 151, 21))
        self.label_validado_o_no.setStyleSheet("font: 11pt Technic; font-style: italic; color: rgb(223, 0, 0);")
        self.label_validado_o_no.setObjectName("label_validado_o_no")
        self.boton_validar = QtWidgets.QPushButton(Dialog)
        self.boton_validar.setGeometry(QtCore.QRect(340, 104, 75, 23))
        self.boton_validar.setStyleSheet("background-color:  rgb(246, 246, 244);")
        self.boton_validar.setObjectName("boton_validar")
        self.input_ancho = QtWidgets.QLineEdit(Dialog)
        self.input_ancho.setGeometry(QtCore.QRect(654, 101, 71, 21))
        self.input_ancho.setObjectName("input_ancho")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(570, 164, 61, 21))
        self.label_6.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(554, -3, 191, 211))
        self.graphicsView_3.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(570, 131, 61, 21))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(571, 99, 81, 21))
        self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.input_largo1 = QtWidgets.QLineEdit(Dialog)
        self.input_largo1.setGeometry(QtCore.QRect(644, 134, 81, 21))
        self.input_largo1.setObjectName("input_largo1")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(571, 66, 81, 21))
        self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(436, -3, 121, 211))
        self.graphicsView_2.setStyleSheet("border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_validacion_2 = QtWidgets.QLabel(Dialog)
        self.label_validacion_2.setGeometry(QtCore.QRect(449, 10, 101, 51))
        self.label_validacion_2.setStyleSheet("font: 13pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_validacion_2.setObjectName("label_validacion_2")
        self.label_dimensiones = QtWidgets.QLabel(Dialog)
        self.label_dimensiones.setGeometry(QtCore.QRect(584, 10, 131, 51))
        self.label_dimensiones.setStyleSheet("font: 13pt \"Technic\";\n"
"color: rgb(69,69,73);")
        self.label_dimensiones.setObjectName("label_dimensiones")
        self.input_largo2 = QtWidgets.QLineEdit(Dialog)
        self.input_largo2.setGeometry(QtCore.QRect(644, 167, 81, 21))
        self.input_largo2.setObjectName("input_largo2")
        self.input_altura = QtWidgets.QLineEdit(Dialog)
        self.input_altura.setGeometry(QtCore.QRect(644, 67, 81, 21))
        self.input_altura.setText("")
        self.input_altura.setObjectName("input_altura")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(461, 100, 51, 21))
        self.label_7.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(460, 132, 61, 21))
        self.label_8.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(460, 165, 61, 21))
        self.label_9.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(461, 67, 51, 21))
        self.label_10.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.inter_L = QtWidgets.QComboBox(Dialog)
        self.inter_L.setGeometry(QtCore.QRect(492, 67, 41, 22))
        self.inter_L.setObjectName("inter_L")
        self.inter_L.addItem("")
        self.inter_L.addItem("")
        self.inter_R = QtWidgets.QComboBox(Dialog)
        self.inter_R.setGeometry(QtCore.QRect(492, 100, 41, 22))
        self.inter_R.setObjectName("inter_R")
        self.inter_R.addItem("")
        self.inter_R.addItem("")
        self.inter_T = QtWidgets.QComboBox(Dialog)
        self.inter_T.setGeometry(QtCore.QRect(492, 133, 41, 22))
        self.inter_T.setObjectName("inter_T")
        self.inter_T.addItem("")
        self.inter_T.addItem("")
        self.inter_P = QtWidgets.QComboBox(Dialog)
        self.inter_P.setGeometry(QtCore.QRect(492, 165, 41, 22))
        self.inter_P.setObjectName("inter_P")
        self.inter_P.addItem("")
        self.inter_P.addItem("")
        self.graphicsView_5 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 204, 321, 481))
        self.graphicsView_5.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_6.setGeometry(QtCore.QRect(316, 205, 471, 481))
        self.graphicsView_6.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_7.setGeometry(QtCore.QRect(784, 205, 241, 321))
        self.graphicsView_7.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.title_label_3 = QtWidgets.QLabel(Dialog)
        self.title_label_3.setGeometry(QtCore.QRect(337, 215, 231, 51))
        self.title_label_3.setStyleSheet("font: 20pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_3.setObjectName("title_label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(745, 0, 281, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("dimensiones.JPG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.title_label_4 = QtWidgets.QLabel(Dialog)
        self.title_label_4.setGeometry(QtCore.QRect(870, 220, 121, 51))
        self.title_label_4.setStyleSheet("font: 20pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_4.setObjectName("title_label_4")
        self.title_label_5 = QtWidgets.QLabel(Dialog)
        self.title_label_5.setGeometry(QtCore.QRect(807, 530, 201, 41))
        self.title_label_5.setStyleSheet("font: 20pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_5.setObjectName("title_label_5")
        self.tabla = QtWidgets.QTableWidget(Dialog)
        self.tabla.setGeometry(QtCore.QRect(20, 251, 281, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla.sizePolicy().hasHeightForWidth())
        self.tabla.setSizePolicy(sizePolicy)
        self.tabla.setStyleSheet("font-size: 11px;\n"
" border-collapse: collapse;\n"
"text-align: center;")
        self.tabla.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla.setRowCount(21)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(3, item)
        self.tabla.horizontalHeader().setVisible(False)
        self.tabla.verticalHeader().setVisible(False)
        self.label_main_data = QtWidgets.QLabel(Dialog)
        self.label_main_data.setGeometry(QtCore.QRect(840, 282, 81, 21))
        self.label_main_data.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data.setObjectName("label_main_data")
        self.label_main_data_2 = QtWidgets.QLabel(Dialog)
        self.label_main_data_2.setGeometry(QtCore.QRect(840, 322, 81, 21))
        self.label_main_data_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data_2.setObjectName("label_main_data_2")
        self.label_main_data_3 = QtWidgets.QLabel(Dialog)
        self.label_main_data_3.setGeometry(QtCore.QRect(840, 362, 81, 21))
        self.label_main_data_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data_3.setObjectName("label_main_data_3")
        self.label_main_data_4 = QtWidgets.QLabel(Dialog)
        self.label_main_data_4.setGeometry(QtCore.QRect(840, 402, 81, 21))
        self.label_main_data_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data_4.setObjectName("label_main_data_4")
        self.label_main_data_5 = QtWidgets.QLabel(Dialog)
        self.label_main_data_5.setGeometry(QtCore.QRect(840, 442, 81, 21))
        self.label_main_data_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data_5.setObjectName("label_main_data_5")
        self.label_main_data_6 = QtWidgets.QLabel(Dialog)
        self.label_main_data_6.setGeometry(QtCore.QRect(840, 482, 81, 21))
        self.label_main_data_6.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_main_data_6.setObjectName("label_main_data_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(806, 573, 201, 61))
        self.textBrowser_2.setStyleSheet("border: 0px;\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42,78,102);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(337, 270, 431, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exportar_excel = QtWidgets.QPushButton(Dialog)
        self.exportar_excel.setGeometry(QtCore.QRect(867, 640, 75, 23))
        self.exportar_excel.setObjectName("exportar_excel")
        self.graphicsView_8 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_8.setGeometry(QtCore.QRect(783, 522, 241, 164))
        self.graphicsView_8.setStyleSheet("background-color: rgb(42,78,102);\n"
"border: 4px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.label_tabla = QtWidgets.QLabel(Dialog)
        self.label_tabla.setGeometry(QtCore.QRect(20, 221, 281, 31))
        self.label_tabla.setStyleSheet("font: 10pt \"Technic\";\n"
"font: 25 8pt \"Microsoft YaHei Light\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);\n"
"border: 2px;\n"
"border-color: rgb(246, 246, 244);\n"
"border-style:  groove;")
        self.label_tabla.setObjectName("label_tabla")
        self.label_L1_db = QtWidgets.QLabel(Dialog)
        self.label_L1_db.setGeometry(QtCore.QRect(922, 284, 81, 21))
        self.label_L1_db.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_L1_db.setText("")
        self.label_L1_db.setObjectName("label_L1_db")
        self.label_L2_dB = QtWidgets.QLabel(Dialog)
        self.label_L2_dB.setGeometry(QtCore.QRect(923, 325, 91, 21))
        self.label_L2_dB.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_L2_dB.setText("")
        self.label_L2_dB.setObjectName("label_L2_dB")
        self.label_L1_dBA = QtWidgets.QLabel(Dialog)
        self.label_L1_dBA.setGeometry(QtCore.QRect(923, 365, 91, 21))
        self.label_L1_dBA.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_L1_dBA.setText("")
        self.label_L1_dBA.setObjectName("label_L1_dBA")
        self.label_L2_dBA = QtWidgets.QLabel(Dialog)
        self.label_L2_dBA.setGeometry(QtCore.QRect(923, 405, 91, 21))
        self.label_L2_dBA.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_L2_dBA.setText("")
        self.label_L2_dBA.setObjectName("label_L2_dBA")
        self.label_dif_dB = QtWidgets.QLabel(Dialog)
        self.label_dif_dB.setGeometry(QtCore.QRect(923, 445, 91, 21))
        self.label_dif_dB.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_dif_dB.setText("")
        self.label_dif_dB.setObjectName("label_dif_dB")
        self.label_dif_dBA = QtWidgets.QLabel(Dialog)
        self.label_dif_dBA.setGeometry(QtCore.QRect(923, 485, 91, 21))
        self.label_dif_dBA.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_dif_dBA.setText("")
        self.label_dif_dBA.setObjectName("label_dif_dBA")
        self.boton_informacion = QtWidgets.QPushButton(Dialog)
        self.boton_informacion.setGeometry(QtCore.QRect(750, 180, 21, 21))
        self.boton_informacion.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"font: 75 8pt \"Nirmala UI\";\n"
"border: 2px;")
        self.boton_informacion.setObjectName("boton_informacion")
        self.graphicsView_8.raise_()
        self.label_2.raise_()
        self.graphicsView_3.raise_()
        self.graphicsView_4.raise_()
        self.graphicsView.raise_()
        self.title_label.raise_()
        self.title_label_2.raise_()
        self.label.raise_()
        self.browse_button.raise_()
        self.mostrar_archivo.raise_()
        self.label_validacion.raise_()
        self.label_validado_o_no.raise_()
        self.boton_validar.raise_()
        self.input_ancho.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.input_largo1.raise_()
        self.label_3.raise_()
        self.graphicsView_2.raise_()
        self.label_validacion_2.raise_()
        self.label_dimensiones.raise_()
        self.input_largo2.raise_()
        self.input_altura.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.inter_L.raise_()
        self.inter_R.raise_()
        self.inter_T.raise_()
        self.inter_P.raise_()
        self.graphicsView_5.raise_()
        self.graphicsView_6.raise_()
        self.title_label_3.raise_()
        self.graphicsView_7.raise_()
        self.title_label_4.raise_()
        self.title_label_5.raise_()
        self.tabla.raise_()
        self.label_main_data.raise_()
        self.label_main_data_2.raise_()
        self.label_main_data_3.raise_()
        self.label_main_data_4.raise_()
        self.label_main_data_5.raise_()
        self.label_main_data_6.raise_()
        self.textBrowser_2.raise_()
        self.frame.raise_()
        self.exportar_excel.raise_()
        self.label_tabla.raise_()
        self.label_L1_db.raise_()
        self.label_L2_dB.raise_()
        self.label_L1_dBA.raise_()
        self.label_L2_dBA.raise_()
        self.label_dif_dB.raise_()
        self.label_dif_dBA.raise_()
        self.boton_informacion.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Acoustic Data"))
        self.title_label_2.setText(_translate("Dialog", "flancos"))
        self.label.setText(_translate("Dialog", "Carga de datos:"))
        self.browse_button.setText(_translate("Dialog", "Buscar"))
        self.label_validacion.setText(_translate("Dialog", "Validación de datos:"))
        self.label_validado_o_no.setText(_translate("Dialog", "ingrese los datos"))
        self.boton_validar.setText(_translate("Dialog", "Validar"))
        self.label_6.setText(_translate("Dialog", "Largo 2:"))
        self.label_5.setText(_translate("Dialog", "Largo 1:"))
        self.label_4.setText(_translate("Dialog", "Ancho (W):"))
        self.label_3.setText(_translate("Dialog", "Altura (H):"))
        self.label_validacion_2.setText(_translate("Dialog", "Intersección"))
        self.label_dimensiones.setText(_translate("Dialog", "dimensiones sala"))
        self.label_7.setText(_translate("Dialog", "R:"))
        self.label_8.setText(_translate("Dialog", "T:"))
        self.label_9.setText(_translate("Dialog", "P:"))
        self.label_10.setText(_translate("Dialog", "L:"))
        self.inter_L.setItemText(0, _translate("Dialog", "X"))
        self.inter_L.setItemText(1, _translate("Dialog", "T"))
        self.inter_R.setItemText(0, _translate("Dialog", "X"))
        self.inter_R.setItemText(1, _translate("Dialog", "T"))
        self.inter_T.setItemText(0, _translate("Dialog", "X"))
        self.inter_T.setItemText(1, _translate("Dialog", "T"))
        self.inter_P.setItemText(0, _translate("Dialog", "X"))
        self.inter_P.setItemText(1, _translate("Dialog", "T"))
        self.title_label_3.setText(_translate("Dialog", "Gráfico Flancos"))
        self.title_label_4.setText(_translate("Dialog", "Datos"))
        self.title_label_5.setText(_translate("Dialog", "Exportar Datos"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "F (Hz)"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "L1 (dB)"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "R (dB)"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "L2(dB)"))
        self.label_main_data.setText(_translate("Dialog", "L1 Total:"))
        self.label_main_data_2.setText(_translate("Dialog", "L2 Total:"))
        self.label_main_data_3.setText(_translate("Dialog", "L1 Total:"))
        self.label_main_data_4.setText(_translate("Dialog", "L2 Total:"))
        self.label_main_data_5.setText(_translate("Dialog", "Diferencia:"))
        self.label_main_data_6.setText(_translate("Dialog", "Diferencia:"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Los datos serán exportados a un excel con los valores de la tabla mas el R por cada flanco.</p></body></html>"))
        self.exportar_excel.setText(_translate("Dialog", "Exportar"))
        self.label_tabla.setText(_translate("Dialog", "      F (Hz)      |       L1 (dB)     |       R (dB)      |      L2 (dB)      |"))
        self.boton_informacion.setText(_translate("Dialog", "?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
