# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datos_plantilla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_2(object):
    def setupUi(self, ventana_2):
        ventana_2.setObjectName("ventana_2")
        ventana_2.resize(331, 443)
        ventana_2.setStyleSheet("background-color: rgb(42,78,102);")
        self.title_label_12 = QtWidgets.QLabel(ventana_2)
        self.title_label_12.setGeometry(QtCore.QRect(30, 10, 321, 51))
        self.title_label_12.setStyleSheet("font: 20pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.title_label_12.setObjectName("title_label_12")
        self.label_11 = QtWidgets.QLabel(ventana_2)
        self.label_11.setGeometry(QtCore.QRect(40, 70, 61, 31))
        self.label_11.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(ventana_2)
        self.label_12.setGeometry(QtCore.QRect(40, 110, 131, 31))
        self.label_12.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(ventana_2)
        self.label_13.setGeometry(QtCore.QRect(40, 230, 151, 31))
        self.label_13.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(ventana_2)
        self.label_14.setGeometry(QtCore.QRect(40, 190, 141, 31))
        self.label_14.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(ventana_2)
        self.label_15.setGeometry(QtCore.QRect(40, 150, 101, 31))
        self.label_15.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(ventana_2)
        self.label_16.setGeometry(QtCore.QRect(40, 270, 91, 31))
        self.label_16.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(42,78,102);\n"
"color: rgb(246, 246, 244);")
        self.label_16.setObjectName("label_16")
        self.input_cliente = QtWidgets.QLineEdit(ventana_2)
        self.input_cliente.setGeometry(QtCore.QRect(110, 77, 201, 21))
        self.input_cliente.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.input_cliente.setText("")
        self.input_cliente.setObjectName("input_cliente")
        self.input_fecha_ensayo = QtWidgets.QLineEdit(ventana_2)
        self.input_fecha_ensayo.setGeometry(QtCore.QRect(180, 118, 131, 21))
        self.input_fecha_ensayo.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.input_fecha_ensayo.setText("")
        self.input_fecha_ensayo.setObjectName("input_fecha_ensayo")
        self.input_fecha_actual = QtWidgets.QLineEdit(ventana_2)
        self.input_fecha_actual.setGeometry(QtCore.QRect(150, 158, 161, 21))
        self.input_fecha_actual.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.input_fecha_actual.setText("")
        self.input_fecha_actual.setObjectName("input_fecha_actual")
        self.input_instituto_ensayo = QtWidgets.QLineEdit(ventana_2)
        self.input_instituto_ensayo.setGeometry(QtCore.QRect(180, 198, 131, 21))
        self.input_instituto_ensayo.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.input_instituto_ensayo.setText("")
        self.input_instituto_ensayo.setObjectName("input_instituto_ensayo")
        self.input_num_ensayo = QtWidgets.QLineEdit(ventana_2)
        self.input_num_ensayo.setGeometry(QtCore.QRect(200, 238, 111, 21))
        self.input_num_ensayo.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.input_num_ensayo.setText("")
        self.input_num_ensayo.setObjectName("input_num_ensayo")
        self.text_descripcion = QtWidgets.QTextEdit(ventana_2)
        self.text_descripcion.setGeometry(QtCore.QRect(40, 310, 271, 71))
        self.text_descripcion.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"border: 1px;\n"
"border-color: rgb(95, 95, 95);\n"
"border-style: ridge;")
        self.text_descripcion.setObjectName("text_descripcion")
        self.guardar_plantilla = QtWidgets.QPushButton(ventana_2)
        self.guardar_plantilla.setGeometry(QtCore.QRect(238, 403, 75, 23))
        self.guardar_plantilla.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.guardar_plantilla.setObjectName("guardar_plantilla")
        self.label_guardado = QtWidgets.QLabel(ventana_2)
        self.label_guardado.setGeometry(QtCore.QRect(40, 385, 141, 51))
        self.label_guardado.setStyleSheet("font: 10pt \"Technic\";\n"
"color: rgb(246, 246, 244);\n"
"background-color: rgb(42, 78, 102);")
        self.label_guardado.setObjectName("label_guardado")

        self.retranslateUi(ventana_2)
        QtCore.QMetaObject.connectSlotsByName(ventana_2)

    def retranslateUi(self, ventana_2):
        _translate = QtCore.QCoreApplication.translate
        ventana_2.setWindowTitle(_translate("ventana_2", "Dialog"))
        self.title_label_12.setText(_translate("ventana_2", "Datos Plantilla PDF"))
        self.label_11.setText(_translate("ventana_2", "Cliente: "))
        self.label_12.setText(_translate("ventana_2", "Fecha del ensayo:"))
        self.label_13.setText(_translate("ventana_2", "Número del Informe:"))
        self.label_14.setText(_translate("ventana_2", "Instituo del ensayo:"))
        self.label_15.setText(_translate("ventana_2", "Fecha actual:"))
        self.label_16.setText(_translate("ventana_2", "Descripción:"))
        self.guardar_plantilla.setText(_translate("ventana_2", "Guardar"))
        self.label_guardado.setText(_translate("ventana_2", "Datos no guardados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_2 = QtWidgets.QDialog()
    ui = Ui_ventana_2()
    ui.setupUi(ventana_2)
    ventana_2.show()
    sys.exit(app.exec_())
